# Generated by Django 3.2.8 on 2021-10-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_id', models.CharField(max_length=20, unique=True)),
                ('pipeline_name', models.CharField(max_length=50, unique=True)),
                ('pipeline_des', models.TextField()),
                ('created_by', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('AOI', models.JSONField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('freq_number', models.PositiveIntegerField()),
                ('freq_interval', models.CharField(max_length=20, unique=True)),
                ('cloud_cover', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resolution', models.CharField(max_length=20, unique=True)),
                ('output_format', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
