# Generated by Django 3.2.8 on 2021-10-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0002_auto_20211017_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinelist',
            name='AOI',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='pipelinelist',
            name='created_by',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pipelinelist',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pipelinelist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
