# Generated by Django 3.2.8 on 2021-10-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0003_auto_20211017_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinelist',
            name='AOI',
        ),
    ]
