# Generated by Django 3.2.8 on 2021-10-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0004_remove_pipelinelist_aoi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinelist',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
