# Generated by Django 3.2.8 on 2021-10-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0005_alter_pipelinelist_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_id', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'satellite ids',
            },
        ),
    ]
