# Generated by Django 3.2.8 on 2021-10-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0006_pipelineresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipeLineChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sat_num', models.CharField(max_length=2)),
            ],
        ),
    ]
