# Generated by Django 3.2.8 on 2021-10-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0007_pipelinechoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinechoice',
            name='user_sat_num',
            field=models.CharField(max_length=50),
        ),
    ]
