# Generated by Django 3.2.8 on 2021-10-19 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0008_alter_pipelinechoice_user_sat_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinechoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
