# Generated by Django 3.2.8 on 2021-10-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0009_pipelinechoice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinechoice',
            name='user_sat_num',
            field=models.IntegerField(),
        ),
    ]
