# Generated by Django 3.2.8 on 2021-10-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0012_auto_20211027_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PipeLineChoice',
        ),
        migrations.DeleteModel(
            name='PipelineResults',
        ),
    ]
