# Generated by Django 3.2.8 on 2021-10-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0013_auto_20211030_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinelist',
            name='AOI',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='pipelinelist',
            name='cloud_cover',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pipelinelist',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pipelinelist',
            name='freq_interval',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pipelinelist',
            name='freq_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelinelist',
            name='output_format',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pipelinelist',
            name='resolution',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pipelinelist',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
