# Generated by Django 3.2.8 on 2021-10-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0014_auto_20211030_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinelist',
            name='output_format',
            field=models.CharField(choices=[('a', 'Hola'), ('b', 'Hello'), ('c', 'Bonjour'), ('d', 'Boas')], max_length=1, null=True),
        ),
    ]
