# Generated by Django 3.2.8 on 2021-10-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0015_alter_pipelinelist_output_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinelist',
            name='AOI',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelinelist',
            name='pipeline_id',
            field=models.CharField(max_length=20),
        ),
    ]
