# Generated by Django 3.2.8 on 2021-11-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceport', '0017_pipelinelist_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_pipeline_id', models.CharField(blank=True, max_length=200)),
                ('results_status', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='pipelinelist',
            name='unique_api_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
